version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-network

  php:
    build: .docker/php
    container_name: "php-srv"
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - net-network

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - net-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - net-network

networks:
    net-network:
        driver: bridge
